export type Product = {
  id: number
  slug: string
  name: string
  category: string
  image: string
  tagline: string
  description: string
  howToUse: string
  ingredients: string
  benefits: string[]
  specialFeatures: string[]
  tags: string[]
  variants: Array<{ weight: string; price: number }>
  relatedCategories?: string[]
}

export const productsData = [
  // SOAPS (6 products)
  {
    id: 1,
    slug: "charcoal-coffee-soap",
    name: "Charcoal & Coffee Soap",
    category: "Soaps",
    image: "/images/coffee-2btea-20tree-20soap.jpg",
    tagline: "Exfoliating | Detoxifying | Brightening | Natural Skincare",
    description:
      "Reveal glowing, even-toned skin with our Butter-Rich Coffee + Tea Tree Soap — a luxurious bar made with raw coffee, activated charcoal, and tea tree oil. This gentle exfoliating soap helps remove dead skin cells, repair damaged skin, and balance oil production without stripping moisture from your skin.",
    howToUse:
      "Wet skin with lukewarm water. Lather the soap bar between your hands or with a loofah. Massage gently over face and body. Rinse thoroughly.",
    ingredients: "Raw coffee grounds, activated charcoal, tea tree oil, shea butter, coconut oil, vitamin E",
    benefits: [
      "Gently exfoliates for radiant, smoother skin",
      "Helps fade the effects of harsh skincare or bleaching products",
      "Balances oily skin with tea tree's natural properties",
      "Creamy, hydrating lather that cleanses deeply",
      "Supports skin healing and glow-up naturally",
    ],
    specialFeatures: [
      "100% Preservative-free & sulfate-free",
      "Plastic-free, recyclable packaging",
      "Handmade by women",
      "Ethically and sustainably sourced in Africa",
      "Made with skin-loving, nutrient-rich ingredients",
    ],
    tags: [
      "coffee soap",
      "exfoliating soap",
      "tea tree soap",
      "natural skincare",
      "charcoal soap",
      "eco-friendly",
      "handmade in Africa",
      "skin brightening",
      "sulfate free",
      "plastic free",
    ],
    variants: [
      { weight: "170g", price: 5000 },
      { weight: "40g", price: 1500 },
      { weight: "Multi Pack (3pcs)", price: 13800 },
    ],
    relatedCategories: ["Soaps", "Skincare"],
  },
  {
    id: 2,
    slug: "african-black-soap-bar",
    name: "African Black Soap Bar",
    category: "Soaps",
    image: "/images/raw-20african-20blacksoap.jpg",
    tagline: "Deep Cleansing | Clarifying | Balancing | Natural Skincare",
    description:
      "Our Authentic African Black Soap Bar is a traditional, plant-based cleanser handcrafted with nutrient-rich African ingredients. Known for its deep cleansing and skin-balancing properties, this gentle yet powerful bar helps clarify the skin, reduce blemishes, and improve overall texture. Perfect for daily use and suitable for all skin types, especially acne-prone, oily, or troubled skin.",
    howToUse:
      "Wet skin with lukewarm water. Lather the soap bar between your hands or with a loofah. Massage gently over face and body. Rinse thoroughly.",
    ingredients: "Plantain skin ash, coconut oil, shea butter, palm oil, cocoa pod ash, natural plant extracts",
    benefits: [
      "Deep cleanses without over-drying",
      "Helps reduce acne, blemishes, and clogged pores",
      "Supports a clearer, smoother, more balanced complexion",
      "Naturally reduces excess oil and impurities",
      "Gentle, soothing, and suitable for everyday use",
    ],
    specialFeatures: [
      "100% Preservative-free, sulfate-free & fragrance-free",
      "Packaged in plastic-free, recyclable boxes",
      "Handmade by women using traditional African techniques",
      "Ethically and sustainably sourced ingredients",
      "Rich in vitamins, antioxidants & plant-based goodness",
    ],
    tags: [
      "african black soap",
      "organic black soap",
      "natural cleanser",
      "acne soap",
      "clarifying soap",
      "handmade soap",
      "eco-friendly beauty",
      "African skincare",
      "sulfate free soap",
      "plastic free",
    ],
    variants: [
      { weight: "170g", price: 5000 },
      { weight: "40g", price: 1500 },
      { weight: "Multi Pack (3pcs)", price: 13800 },
    ],
    relatedCategories: ["Soaps", "Skincare"],
  },
  {
    id: 3,
    slug: "shea-butter-blend-soap",
    name: "Shea Butter Blend Soap",
    category: "Soaps",
    image: "/images/shea-20butter-20soap.jpg",
    tagline: "Moisturizing | Soothing | Gentle | Sensitive Skin Friendly",
    description:
      "Our Shea Butter Blend Soap is a gentle, ultra-moisturizing bar specially crafted for dry, sensitive, or eczema-prone skin. Made with raw shea butter, it forms a rich, creamy lather that soothes irritation, restores softness, and hydrates deeply — perfect for daily use on delicate skin.",
    howToUse:
      "Wet skin with lukewarm water. Lather the soap bar between your hands or with a loofah. Massage gently over face and body. Rinse thoroughly.",
    ingredients: "Raw shea butter, coconut oil, palm kernel oil, vitamin E, natural fragrance",
    benefits: [
      "Calms eczema and soothes irritated skin",
      "Deeply moisturizes without clogging pores",
      "Gentle enough for babies and sensitive skin",
      "Creamy lather leaves skin soft and nourished",
      "Balances skin naturally",
    ],
    specialFeatures: [
      "Preservative-free & sulfate-free",
      "Plastic-free, recyclable packaging",
      "Handmade by women",
      "Ethically and sustainably sourced in Africa",
      "Made with pure, nourishing ingredients",
    ],
    tags: [
      "shea butter soap",
      "eczema relief",
      "moisturizing soap",
      "gentle cleanser",
      "natural skincare",
      "handmade soap",
      "African skincare",
      "eco-friendly beauty",
      "multipurpose balm",
      "moisturizing balm",
    ],
    variants: [
      { weight: "170g", price: 5000 },
      { weight: "40g", price: 1500 },
      { weight: "Multi Pack (3pcs)", price: 13800 },
    ],
    relatedCategories: ["Soaps", "Skincare"],
  },
  {
    id: 4,
    slug: "carrot-oil-blend-soap",
    name: "Carrot Oil Blend Soap",
    category: "Soaps",
    image: "/images/carrot-soap.jpg",
    tagline: "Brightening | Hydrating | Gentle | Natural Skincare",
    description:
      "Our Nourishing Carrot Glow Soap is a creamy, moisturizing bar made with skin-loving natural ingredients to brighten and smooth your skin. Rich in nutrients from carrot extracts, this gentle cleanser helps hydrate, balance oily skin, and promote a more radiant, even tone. Perfect for daily use and suitable for all skin types — especially dull, tired, or uneven skin.",
    howToUse:
      "Wet skin with lukewarm water. Lather the soap bar between your hands or with a loofah. Massage gently over face and body. Rinse thoroughly.",
    ingredients:
      "Carrot seed oil, carrot root extract, shea butter, coconut oil, vitamin A, natural fragrance, vitamin E",
    benefits: [
      "Boosts skin radiance and glow",
      "Hydrates and softens with creamy, non-drying lather",
      "Helps even out skin tone and reduce dullness",
      "Balances oily skin naturally",
      "Safe, gentle, and moisturizing for everyday use",
    ],
    specialFeatures: [
      "100% Preservative-free & sulfate-free",
      "Packaged in plastic-free, recyclable boxes",
      "Handmade by women",
      "Ethically and sustainably sourced in Africa",
      "Made with rich, nourishing, plant-based ingredients",
    ],
    tags: [
      "carrot soap",
      "skin brightening soap",
      "glowing skin",
      "natural skincare",
      "handmade soap",
      "eco-friendly beauty",
      "African skincare",
      "sulfate free soap",
      "plastic free",
      "moisturizing soap",
    ],
    variants: [
      { weight: "170g", price: 5000 },
      { weight: "40g", price: 1500 },
      { weight: "Multi Pack (3pcs)", price: 13800 },
    ],
    relatedCategories: ["Soaps", "Skincare"],
  },
  {
    id: 5,
    slug: "oats-honey-soap",
    name: "Oats & Honey Soap",
    category: "Soaps",
    image: "/images/oats-20-2b-20honey2.jpg",
    tagline: "Soothing | Moisturizing | Gentle Exfoliation | Sensitive Skin Safe",
    description:
      "Our Oats + Honey Soap is a soothing, ultra-gentle exfoliating bar made to nourish and hydrate dry, sensitive, or eczema-prone skin. Formulated with wild honey and ground oats, this creamy soap calms irritation, reduces flakes, and leaves skin soft, balanced, and glowing. Perfect for extremely dry or sensitive skin, and safe for daily use.",
    howToUse:
      "Wet skin with lukewarm water. Lather the soap bar between your hands or with a loofah. Massage gently over face and body. Rinse thoroughly.",
    ingredients:
      "Oatmeal (colloidal oats), raw honey, shea butter, coconut oil, honey extract, vitamin E, natural fragrance",
    benefits: [
      "Gently exfoliates with oats to remove dry flakes",
      "Soothes eczema and nourishes irritated skin",
      "Deeply moisturizes with wild honey",
      "Balances oily skin without stripping natural oils",
      "Creamy lather cleanses while softening the skin",
    ],
    specialFeatures: [
      "100% Preservative-free & sulfate-free",
      "Plastic-free, recyclable packaging",
      "Handmade by women",
      "Ethically and sustainably sourced in Africa",
      "Made with super-nourishing, skin-loving ingredients",
    ],
    tags: [
      "oats and honey soap",
      "eczema soap",
      "gentle exfoliating soap",
      "natural skincare",
      "dry skin relief",
      "African handmade soap",
      "sulfate free soap",
      "plastic free packaging",
      "moisturizing soap",
      "sensitive skin",
    ],
    variants: [
      { weight: "170g", price: 5000 },
      { weight: "40g", price: 1500 },
      { weight: "Multi Pack (3pcs)", price: 13800 },
    ],
    relatedCategories: ["Soaps", "Skincare"],
  },
  {
    id: 6,
    slug: "neem-oil-blend-soap",
    name: "Neem Oil Blend Soap",
    category: "Soaps",
    image: "/images/Neemoilblendsoap.jpg",
    tagline: "Clarifying | Healing | Anti-Blemish | Herbal Skincare",
    description:
      "Our Neem Oil Blend Soap is a powerful herbal bar infused with pure neem oil, known for its antibacterial, anti-inflammatory, and skin-balancing properties. This soap is designed to target blemishes, body acne, and skin irritation while still being gentle enough for daily use. Blended with skin-soothing oils and natural butters, it helps detoxify the skin, reduce excess oil, and calm conditions like eczema and breakouts — all without drying you out. Perfect for oily, acne-prone, or irritated skin.",
    howToUse:
      "Wet skin with lukewarm water. Lather the soap bar between your hands or with a loofah. Massage gently over face and body. Rinse thoroughly.",
    ingredients: "Neem oil, tea tree oil, shea butter, coconut oil, vitamin E",
    benefits: [
      "Fights acne and blemishes naturally",
      "Soothes inflamed, itchy, or irritated skin",
      "Balances sebum production for clearer skin",
      "Deeply cleanses while maintaining skin hydration",
      "Great for face and body use",
    ],
    specialFeatures: [
      "Made with pure Neem oil, known for its medicinal skincare benefits",
      "100% preservative-free & sulphate-free",
      "Packaged in plastic-free, recyclable boxes",
      "Handmade by women",
      "Ethically and sustainably sourced in Africa",
      "Infused with herbal, super-nourishing ingredients for radiant, healthy skin",
    ],
    tags: [
      "neem oil soap",
      "acne soap",
      "herbal soap",
      "natural antibacterial soap",
      "African neem skincare",
      "eco-friendly packaging",
      "handmade soap",
      "blemish treatment",
      "sulfate free",
      "plastic free",
    ],
    variants: [
      { weight: "170g", price: 5000 },
      { weight: "40g", price: 1500 },
      { weight: "Multi Pack (3pcs)", price: 13800 },
    ],
    relatedCategories: ["Soaps", "Skincare"],
  },

  // BALMS & OILS (4 products)
  {
    id: 7,
    slug: "raw-unrefined-shea-butter",
    name: "Raw Unrefined Shea Butter",
    category: "Balms & Oils",
    image: "/images/unrefined-20shea-butter.jpg",
    tagline: "Pure | Multi-Purpose | Moisturizing | Plastic-Free Packaging",
    description:
      "Our Raw Unrefined Shea Butter is 100% pure, ivory-colored, and packed with nourishing goodness. Soft to the touch and quick to melt into skin and hair, it delivers deep hydration and natural protection for all skin types. Ideal for DIY lovers, this butter is incredibly versatile — use it as a body balm, hair mask, baby lotion, lip salve, and more.",
    howToUse:
      "Apply to damp skin after bathing or showering. Use as a bath oil, massage oil, or daily body moisturizer. Add to your scalp or hair for shine and nourishment.",
    ingredients: "100% Pure Unrefined Shea Butter",
    benefits: [
      "Deeply moisturizes skin, hair, lips, and cuticles",
      "Supports skin healing and soothes irritation",
      "Perfect for DIY skincare and haircare blends",
      "Rich in vitamins A, E & essential fatty acids",
      "Safe for sensitive skin, babies, and all skin types",
    ],
    specialFeatures: [
      "100% Raw, pure & unrefined",
      "Preservative-free & fragrance-free",
      "Packaged in an eco-friendly refill pouch",
      "Handmade by women",
      "Ethically and sustainably sourced in Africa",
      "Soft, smooth, and truly natural",
    ],
    tags: [
      "raw shea butter",
      "unrefined shea",
      "organic body butter",
      "African shea butter",
      "DIY skincare",
      "natural moisturizer",
      "fragrance free",
      "eco refill",
      "plastic free packaging",
      "handmade in Africa",
    ],
    variants: [
      { weight: "1kg", price: 10000 },
      { weight: "250g", price: 3500 },
      { weight: "100g", price: 1500 },
    ],
    relatedCategories: ["Soaps", "Skincare"],
  },
  {
    id: 8,
    slug: "shea-cocoa-balm",
    name: "Shea Cocoa Balm",
    category: "Balms & Oils",
    image: "/images/shea-20cocoa-20balm.jpg",
    tagline: "Lightweight | Non-Greasy | Multipurpose | Glow Enhancing",
    description:
      "Wrap your skin in nature's softest touch with our Shea Body Oil, a luxuriously light yet deeply hydrating blend made from pure shea oil and botanical extracts. It's designed to moisturize, nourish, and restore your skin's natural glow — without feeling heavy or greasy. Perfect for dry, dull, or uneven skin, this oil absorbs quickly, leaving you soft, silky, and radiant all day.",
    howToUse:
      "Apply to damp skin after bathing or showering. Use as a bath oil, massage oil, or daily body moisturizer. Add to your scalp or hair for shine and nourishment.",
    ingredients: "Shea butter, shea oil, coconut oil, vitamin E, natural botanical extracts",
    benefits: [
      "Lightweight and fast-absorbing",
      "Locks in moisture and softens dry skin",
      "Helps improve skin tone and elasticity",
      "Natural glow enhancer for all skin types",
      "Can be used on hair, scalp, and nails too!",
    ],
    specialFeatures: [
      "Made with pure shea oil from Africa",
      "100% preservative-free, fragrance-free & synthetic-free",
      "Packaged in a refillable, Eco-friendly bottle",
      "Handmade by women",
      "Ethically and sustainable sourced ingredients",
      "Suitable for children, sensitive skin, and all skin tones",
    ],
    tags: [
      "shea body oil",
      "natural body oil",
      "African shea oil",
      "glowing skin",
      "dry skin remedy",
      "organic moisturizer",
      "handmade skincare",
      "sustainable beauty",
      "women-made products",
      "plastic-free skincare",
    ],
    variants: [
      { weight: "100ml", price: 6500 },
      { weight: "Multi Pack (3pcs)", price: 18000 },
    ],
    relatedCategories: ["Soaps", "Skincare"],
  },
  {
    id: 9,
    slug: "neem-balm",
    name: "Neem Balm",
    category: "Balms & Oils",
    image: "/images/neembalm.jpg",
    tagline: "Soothing | Healing | Purifying | Natural Skincare",
    description:
      "Our Neem Balm is a rich, concentrated healing salve crafted to soothe irritation, calm inflammation, and support clearer, healthier-looking skin. Infused with potent neem oil and nourishing plant butters, this gentle balm melts effortlessly into the skin, delivering long-lasting moisture and relief. Perfect for dry patches, blemish-prone areas, rashes, insect bites, and sensitive skin that needs extra care. Ideal for face and body — and safe for daily use.",
    howToUse: "Apply to clean, dry skin. Massage gently for absorption. Use 2-3 times daily as needed.",
    ingredients: "Neem oil, shea butter, coconut oil, tea tree oil, vitamin E",
    benefits: [
      "Helps soothe irritated or inflamed skin",
      "Naturally targets acne, spots, and troubled areas",
      "Deeply moisturizes dry, rough, or flaky skin",
      "Supports skin repair and barrier protection",
      "Gentle, multipurpose, and suitable for all skin types",
    ],
    specialFeatures: [
      "100% natural & preservative-free",
      "Free from steroids, parabens & synthetic fragrances",
      "Packaged in recyclable, eco-friendly jars",
      "Handmade in small batches",
      "Powered by African botanicals and traditional herbal care",
    ],
    tags: [
      "neem balm",
      "healing balm",
      "skin repair balm",
      "natural skincare",
      "anti-acne balm",
      "soothing salve",
      "African skincare",
      "eco-friendly beauty",
      "multipurpose balm",
      "moisturizing balm",
    ],
    variants: [
      { weight: "100g", price: 6500 },
      { weight: "50g", price: 3500 },
      { weight: "Multi Pack (3pcs)", price: 18000 },
    ],
    relatedCategories: ["Soaps", "Skincare"],
  },
  {
    id: 10,
    slug: "neem-body-oil",
    name: "Neem Body Oil",
    category: "Balms & Oils",
    image: "/images/neemoil.jpg",
    tagline: "Purifying | Repairing | Balancing | Natural Skincare",
    description:
      "Our Neem Body Oil is a lightweight, fast-absorbing blend formulated to calm, purify, and deeply nourish the skin. Powered by the soothing plant extracts of Neem, this body oil helps reduce irritation, balance problem-prone skin, and support a healthy, even-toned glow. Perfect for daily moisturizing, it sinks in effortlessly — leaving skin soft, hydrated, and refreshed without heaviness or residue. Ideal for all skin types, especially sensitive, acne-prone, uneven, or easily irritated skin.",
    howToUse: "Apply to damp skin after bathing. Massage gently until absorbed. Use daily or as needed.",
    ingredients: "Neem oil, coconut oil, tea tree oil, vitamin E",
    benefits: [
      "Helps soothe and calm inflamed or irritated skin",
      "Balances acne-prone and oily areas on the body",
      "Nourishes, softens, and hydrates without clogging pores",
      "Supports clearer, healthier-looking skin",
      "Lightweight, gentle, and perfect for everyday use",
    ],
    specialFeatures: [
      "100% natural, cold-pressed plant oils",
      "Free from preservatives, parabens & mineral oils",
      "Packaged in recyclable, eco-friendly materials",
      "Handmade in small batches",
      "Ethically sourced African botanicals with powerful skin benefits",
    ],
    tags: [
      "neem oil",
      "body oil",
      "anti-acne body oil",
      "natural skincare",
      "soothing oil",
      "organic body oil",
      "African skincare",
      "eco-friendly beauty",
      "lightweight moisturizer",
      "blemish control",
    ],
    variants: [
      { weight: "100ml", price: 6500 },
      { weight: "Multi Pack (3pcs)", price: 18000 },
    ],
    relatedCategories: ["Soaps", "Skincare"],
  },

  // WELLNESS (1 product)
  {
    id: 11,
    slug: "hot-body-balm",
    name: "Hot Body Balm",
    category: "Wellness",
    image: "/images/hot-body-balm-warming-therapy.jpg",
    tagline: "Warming | Soothing | Plant-Based Relief",
    description:
      "Give your body the comfort it craves with our Hot Body Balm — a warming, herbal-infused balm crafted to ease tension, soothe sore muscles, and boost circulation naturally. Infused with ginger, cayenne, menthol, and African healing oils, this balm delivers a gentle heat that penetrates deep into tired muscles and stiff joints. Whether you're managing stress, post-workout soreness, or everyday aches, this balm offers comforting relief — without synthetic ingredients or harsh chemicals.",
    howToUse:
      "Rub a small amount onto affected areas (back, neck, knees, joints, abdomen). Use for massages or before bed for deep relaxation. Avoid broken skin or face; wash hands after use.",
    ingredients: "Ginger extract, cayenne, menthol, shea butter, African healing oils",
    benefits: [
      "Helps relieve body aches, tension & stiffness",
      "Stimulates circulation & warms cold limbs",
      "Great for menstrual cramps and back pain",
      "Fast-absorbing & non-greasy",
      "Perfect for massages and daily use",
    ],
    specialFeatures: [
      "Infused with warming botanicals like ginger & cayenne",
      "100% natural, fragrance-free & preservative-free",
      "Packaged in a plastic-free, eco-conscious container",
      "Handmade by women",
      "Ethically sourced African ingredients",
      "Inspired by traditional African remedies",
    ],
    tags: [
      "warming balm",
      "hot body balm",
      "natural pain relief",
      "herbal balm for aches",
      "menstrual cramp relief",
      "ginger balm",
      "African body care",
      "handmade wellness",
      "eco-friendly balm",
      "women-made skincare",
    ],
    variants: [{ weight: "99g", price: 7000 }],
    relatedCategories: ["Soaps", "Skincare"],
  },
]
