export const productsData = [
  {
    id: 1,
    slug: "oats-honey-soap",
    name: "Oats + Honey Soap",
    price: 3500,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Oats%20%2B%20Honey2-5Uo8rvbc3x1UVDhcuiTgC4CfWJxHJO.jpg",
    category: "Soaps",
    description: "Our gentle Oats + Honey Soap combines the soothing power of colloidal oatmeal with nature's golden honey to create a luxurious, skin-calming bar. Perfect for sensitive, itchy, or irritated skin, this soap provides natural exfoliation while maintaining moisture balance.",
    howToUse: "Wet soap and lather into wet skin. Rinse with lukewarm water. For deep cleansing use with a loofah sponge. Use twice daily.",
    ingredients: "Oatmeal (colloidal oats), raw honey, shea butter, coconut oil, honey extract, vitamin E, natural fragrance",
    benefits: ["Gently exfoliates", "Soothes irritated skin", "Reduces itching and inflammation", "Moisturizes naturally", "Promotes healthy skin barrier"],
    relatedCategories: "dry skin, sensitive skin, eczema relief, natural soap, oatmeal soap, honey soap",
  },
  {
    id: 2,
    slug: "carrot-soap",
    name: "Carrot Soap",
    price: 3000,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Carrot-Soap-i7OmXx8n82d9xnnK8cOiuoMZYIWmw9.jpg",
    category: "Soaps",
    description: "Our Carrot Oil Blend Soap is enriched with beta-carotene and vitamin A to brighten and revitalize dull skin. This nourishing bar helps improve skin texture, reduce the appearance of blemishes, and leave your skin with a natural, healthy glow.",
    howToUse: "Wet soap and lather into wet skin. Rinse with lukewarm water. For deeper cleansing use with a loofah sponge. Use twice daily.",
    ingredients: "Carrot seed oil, carrot root extract, shea butter, coconut oil, vitamin A, natural fragrance, vitamin E",
    benefits: ["Brightens dull skin", "Reduces blemishes", "Improves skin texture", "Rich in antioxidants", "Promotes natural glow"],
    relatedCategories: "dull skin, brightening, natural soap, antioxidant, carrot oil",
  },
  {
    id: 3,
    slug: "shea-butter-soap",
    name: "Shea Butter Soap",
    price: 3500,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Shea%20butter%20soap-CDkZID9XgYBh7OWGdSvp75BxUs1P3t.jpg",
    category: "Soaps",
    description: "Experience the ultimate hydration with our rich Shea Butter Soap. Loaded with African shea butter and nourishing oils, this creamy bar gently cleanses while maintaining your skin's natural moisture balance. Ideal for dry and sensitive skin.",
    howToUse: "Wet soap and lather into wet skin. Rinse with lukewarm water. For deep cleansing use with a loofah sponge. Use twice daily.",
    ingredients: "Shea butter, coconut oil, palm kernel oil, vitamin E, natural fragrance",
    benefits: ["Deeply moisturizes", "Prevents dryness", "Soothes sensitive skin", "Rich creamy lather", "Non-stripping cleanser"],
    relatedCategories: "dry skin, moisturizing, shea butter, natural soap, sensitive skin",
  },
  {
    id: 4,
    slug: "coffee-tea-tree-soap",
    name: "Coffee + Tea Tree Soap",
    price: 3500,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Coffee%2Btea%20tree%20soap-sXZLtbgenvGa3Ox5lOnc4FHkFYiJkh.jpg",
    category: "Soaps",
    description: "Our butter-rich Coffee + Tea Tree Soap is exfoliating and can help improve the skin's natural glow. It's formulated with raw coffee, activated charcoal, and tea tree oil to exfoliate, repair damaged skin, and balance oil production.",
    howToUse: "Wet soap and lather into wet skin. Rinse with lukewarm water. For deep cleansing use with a loofah sponge. Use twice daily.",
    ingredients: "Raw coffee grounds, tea tree essential oil, activated charcoal, shea butter, coconut oil, vitamin E",
    benefits: ["Gently exfoliates", "Helps fade harsh bleaching effects", "Balances oily skin", "Repairs damaged skin", "Creates radiant glow"],
    relatedCategories: "acne-prone, exfoliating, tea tree oil, coffee soap, charcoal soap",
  },
  {
    id: 5,
    slug: "unrefined-shea-butter",
    name: "Unrefined Shea Butter",
    price: 2500,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Unrefined%20Shea-Butter-N7jiY8NLvk84TQYl2IbS5QXUK5O4b5.jpg",
    category: "Butters",
    description: "Pure, unrefined African shea butter that retains all its natural nutrients. Perfect for face, body, and hair care, this versatile butter deeply moisturizes, heals, and nourishes even the most sensitive skin.",
    howToUse: "Apply directly to damp skin for maximum absorption. Use on face, body, and hair. Great for massage and aromatherapy blending.",
    ingredients: "100% Pure Unrefined Shea Butter",
    benefits: ["Deep moisturization", "Rich in vitamins A, E, F", "Healing properties", "Reduces scars and stretch marks", "Anti-inflammatory"],
    relatedCategories: "natural butter, moisturizing, shea butter, dry skin, multi-use",
  },
  {
    id: 6,
    slug: "raw-african-black-soap",
    name: "Raw African Black Soap",
    price: 3500,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Raw%20African%20Blacksoap-rbmF5iSZKBRpoa1NjuumcyPyLWbPmd.jpg",
    category: "Soaps",
    description: "Our Authentic African Black Soap Bar is a traditional, plant-based cleanser handcrafted with nutrient-rich African ingredients. Deep cleansing and skin-balancing, this gentle yet powerful bar helps clarify skin and improve overall texture.",
    howToUse: "Wet soap and lather into wet skin. Rinse with lukewarm water. For deep cleansing use with a loofah sponge. Use twice daily.",
    ingredients: "Plantain skin ash, coconut oil, shea butter, palm oil, cocoa pod ash",
    benefits: ["Deep cleansing", "Balances skin pH", "Reduces blemishes", "Improves skin texture", "Treats various skin conditions"],
    relatedCategories: "deep cleansing, acne, oily skin, African soap, natural",
  },
  {
    id: 7,
    slug: "shea-cocoa-balm",
    name: "Shea Cocoa Balm",
    price: 7000,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Shea-Cocoa-Balm-SlxJQTQF1E8RNGps5SDdpgDfguAejB.jpg",
    category: "Balms",
    description: "Indulge in luxury with our rich Shea Cocoa Balm. This decadent blend combines African shea butter with cocoa butter to create an intensely moisturizing and rejuvenating treatment for face and body.",
    howToUse: "Apply to clean, damp skin. Massage gently until absorbed. Use morning and night for best results.",
    ingredients: "Shea butter, cocoa butter, coconut oil, vitamin E, natural cocoa fragrance",
    benefits: ["Intense moisturization", "Skin rejuvenation", "Reduces fine lines", "Improves elasticity", "Luxurious texture"],
    relatedCategories: "moisturizing balm, luxury skincare, cocoa butter, shea butter",
  },
  {
    id: 8,
    slug: "charcoal-coffee-soap",
    name: "Charcoal and Coffee Soap",
    price: 5000,
    image: "/charcoal-coffee-soap-exfoliating.jpg",
    category: "Soaps",
    description: "Reveal glowing, even-toned skin with our Charcoal and Coffee Soap — a luxurious bar made with raw coffee, activated charcoal, and tea tree oil. This gentle exfoliating soap helps remove dead skin cells, repair damaged skin, and balance oil production without stripping moisture from your skin.",
    howToUse: "Wet soap and lather into wet skin. Rinse with lukewarm water. For deep cleansing use with a loofah sponge. Use twice daily.",
    ingredients: "Raw coffee grounds, activated charcoal, tea tree oil, shea butter, coconut oil, vitamin E, natural fragrance",
    benefits: ["Gently exfoliates for radiant, smoother skin", "Helps fade harsh bleaching effects", "Balances oily skin", "Repairs damaged skin", "Supports skin healing and glow-up naturally"],
    relatedCategories: "exfoliating soap, charcoal soap, coffee soap, dull skin, brightening",
  },
  {
    id: 9,
    slug: "carrot-oil-blend-soap",
    name: "Carrot Oil Blend Soap",
    price: 5000,
    image: "/carrot-oil-blend-soap-brightening.jpg",
    category: "Soaps",
    description: "Our Carrot Oil Blend Soap is enriched with beta-carotene and vitamin A to brighten and revitalize dull skin. This nourishing bar helps improve skin texture, reduce the appearance of blemishes, and leave your skin with a natural, healthy glow.",
    howToUse: "Wet soap and lather into wet skin. Rinse with lukewarm water. For deeper cleansing use with a loofah sponge. Use twice daily.",
    ingredients: "Carrot seed oil, carrot root extract, shea butter, coconut oil, vitamin A, natural fragrance, vitamin E",
    benefits: ["Brightens dull skin", "Reduces blemishes", "Improves skin texture", "Rich in antioxidants", "Promotes natural glow"],
    relatedCategories: "brightening, natural soap, antioxidant, carrot oil, vitamin A",
  },
  {
    id: 10,
    slug: "activated-charcoal-soap",
    name: "Activated Charcoal Soap",
    price: 5000,
    image: "/activated-charcoal-detox-soap.jpg",
    category: "Soaps",
    description: "Deep cleanse and detoxify with our Activated Charcoal Soap. This powerful yet gentle bar draws out impurities, balances oil production, and leaves your skin feeling refreshed and clarified. Perfect for oily, acne-prone, and combination skin.",
    howToUse: "Wet soap and lather into wet skin. Rinse with lukewarm water. For deep cleansing use with a loofah sponge. Use twice daily.",
    ingredients: "Activated charcoal, coconut oil, shea butter, tea tree oil, vitamin E, natural fragrance",
    benefits: ["Deep cleansing and detoxifying", "Clarifies and balances skin", "Reduces blemishes", "Unclogs pores", "Perfect for oily and acne-prone skin"],
    relatedCategories: "detox soap, charcoal soap, acne treatment, oily skin, deep cleanse",
  },
  {
    id: 11,
    slug: "tea-tree-lavender-soap",
    name: "Tea Tree Lavender Soap",
    price: 5000,
    image: "/tea-tree-lavender-soap-soothing.jpg",
    category: "Soaps",
    description: "Experience the perfect blend of tea tree's cleansing power and lavender's soothing aroma with our Tea Tree Lavender Soap. This gentle bar helps combat acne, reduce inflammation, and promotes calm, balanced skin.",
    howToUse: "Wet soap and lather into wet skin. Rinse with lukewarm water. For deep cleansing use with a loofah sponge. Use twice daily.",
    ingredients: "Tea tree essential oil, lavender essential oil, shea butter, coconut oil, vitamin E, natural fragrance",
    benefits: ["Combats acne and blemishes", "Reduces inflammation", "Soothes irritated skin", "Calming lavender aroma", "Balances skin naturally"],
    relatedCategories: "tea tree soap, lavender soap, acne-prone skin, soothing, natural",
  },
]
